preset: recommended
risky: true
enabled:
  - concat_with_spaces
  - const_separation
  - property_separation
  - not_operator_with_successor_space
disabled:
  - concat_without_spaces
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
  name: "*.php"
  not-name: "*.blade.php"